package com.project.HospitalManagmentSystem.dto;

import com.project.HospitalManagmentSystem.enums.PaymentMethod;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentRequestDTO {

    // Amount is NOT accepted from the client.
    // The backend derives it from the doctor's consultationFee to prevent manipulation.

    @NotNull(message = "Payment Method is required")
    private PaymentMethod paymentMethod;

    @NotNull(message = "Appointment ID is required")
    private Long appointmentId;

    // Required only when paymentMethod = CREDIT_CARD
    // Generated by Stripe.js on the frontend using the publishable key
    private String stripeToken;
}